//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retailisation.Model
{
    using Newtonsoft.Json;
    // using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [JsonIgnore]
        public int T_ID { get; set; }
        public int product_id { get; set; }
        public int store_id { get; set; }
        public Nullable<int> quantity { get; set; }

        [JsonIgnore]
        public virtual Product Product { get; set; }

        [JsonIgnore]
        public virtual Store Store { get; set; }
    }
}
