//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retailisation.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RetailisationdbEntities : DbContext
    {
        public RetailisationdbEntities()
            : base("name=RetailisationdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    
        public virtual ObjectResult<sp_getCountrywiseStock_Result> sp_getCountrywiseStock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getCountrywiseStock_Result>("sp_getCountrywiseStock");
        }
    
        public virtual ObjectResult<sp_getNetworkInventory_Result> sp_getNetworkInventory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getNetworkInventory_Result>("sp_getNetworkInventory");
        }
    }
}
